version: 1.0.{build}
image: Visual Studio 2017
before_build:
- cmd: dotnet restore
build:
  project: EventSourcing.NetCore.sln
  verbosity: minimal
services:
  - postgresql95
test:
  categories:
    except: 
      - Exercise
