version: "3"
services:
    #######################################################
    #  Postgres
    #######################################################
    postgres:
        image: clkao/postgres-plv8
        container_name: postgres
        environment:
            POSTGRES_PASSWORD: Password12!
        ports:
            - "5432:5432"
        networks:
            - postgres

    pgadmin:
        image: dpage/pgadmin4
        container_name: pgadmin_container
        environment:
            PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
            PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
            PGADMIN_CONFIG_SERVER_MODE: 'False'
        volumes:
            - pgadmin:/var/lib/pgadmin
        ports:
            - "${PGADMIN_PORT:-5050}:80"
        networks:
            - postgres

    jaeger:
        image: jaegertracing/all-in-one:latest
        ports:
            - "5775:5775/udp"
            - "6831:6831/udp"
            - "6832:6832/udp"
            - "5778:5778"
            - "16686:16686"
            - "14268:14268"
            - "9411:9411"

networks:
    postgres:
        driver: bridge

volumes:
    postgres:
    pgadmin:
