# Build image
FROM mcr.microsoft.com/dotnet/core/sdk:3.1 AS builder
WORKDIR /app

# Copy files
COPY . ./

RUN dotnet restore ./EventSourcing.NetCore.sln
RUN dotnet build ./EventSourcing.NetCore.sln

WORKDIR /app/Sample/BankAccounts/EventSourcing.Sample.Web
RUN dotnet publish -c Debug -o out

# Build runtime image
FROM mcr.microsoft.com/dotnet/core/aspnet:3.1
WORKDIR /app
COPY --from=builder /app/Sample/BankAccounts/EventSourcing.Sample.Web/out .
ENV ASPNETCORE_URLS="http://*:5000"
ENTRYPOINT ["dotnet", "EventSourcing.Sample.Web.dll"]
